"""Protocol definitions — contracts between layers. No implementation here."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from serverV2.core.models import (
    CommunityMachine,
    CreateJobParams,
    DispatchContext,
    DispatchResult,
    InstanceSnapshot,
    PlannedTask,
    RenderJob,
)


# ---------------------------------------------------------------------------
# Fleet Strategy (Strategy pattern)
# ---------------------------------------------------------------------------

@runtime_checkable
class IFleetStrategy(Protocol):

    @property
    def fleet(self) -> str:
        """Stable fleet identifier — "community" | "modal_serverless" | "vast_serverless"."""
        ...

    @property
    def min_frames_per_instance(self) -> int: ...

    def is_enabled(self) -> bool: ...

    def dispatch(self, task: PlannedTask, context: DispatchContext) -> DispatchResult: ...

    def cancel(self, provider_job_id: str) -> None: ...

    def stop_monitoring(self, job_id: str) -> None: ...

    def provider_job_id_from_job(self, job: dict[str, Any]) -> str | None: ...


# ---------------------------------------------------------------------------
# Fleet Client (HTTP adapter — no DB, no threads)
# ---------------------------------------------------------------------------

@runtime_checkable
class IFleetClient(Protocol):

    def dispatch_job(
        self,
        *,
        job_id: str,
        blend_url: str,
        frame_start: int,
        frame_end: int,
        frame_step: int,
        render_overrides_json: str,
    ) -> str: ...

    def cancel_job(self, provider_job_id: str) -> None: ...

    def get_job_status(self, provider_job_id: str) -> dict[str, Any] | None: ...


# ---------------------------------------------------------------------------
# Callback Handler (per-fleet monitoring)
# ---------------------------------------------------------------------------

@runtime_checkable
class ICallbackHandler(Protocol):

    def start_monitoring(
        self,
        *,
        job_id: str,
        provider_job_id: str,
        machine_id: str,
        blend_url: str,
        render_overrides_json: str,
        group_id: str,
    ) -> None: ...


# ---------------------------------------------------------------------------
# Repositories
# ---------------------------------------------------------------------------

class IJobRepository(Protocol):
    def create(self, params: CreateJobParams) -> str: ...
    def get_by_id(self, job_id: str) -> RenderJob | None: ...
    def get_raw_by_id(self, job_id: str) -> dict[str, Any] | None: ...
    def update_status(self, job_id: str, status: str, *, error: str | None = None) -> None: ...
    def update_progress(self, job_id: str, rendered_frames: int, total_frames: int) -> None: ...
    def mark_done(self, job_id: str) -> None: ...
    def mark_failed(self, job_id: str, error: str) -> None: ...
    def get_by_group(self, group_id: str) -> list[RenderJob]: ...
    def get_active_by_group(self, group_id: str) -> list[dict[str, Any]]: ...
    def cancel_active_by_group(self, group_id: str) -> None: ...
    def create_failover_job(self, *, new_job_id: str, failover_machine_id: str, group_id: str, input_filename: str, total_frames: int, frame_start: int, frame_end: int, frame_step: int, render_overrides_json: str, max_retries: int, priority: int, chunk_index: int | None) -> None: ...
    def save_provider_job_id(self, job_id: str, *, provider_job_id: str, column: str) -> None: ...


class IMachineRepository(Protocol):
    """Community machines only.  Serverless fleets are described by
    FleetCapability (no machine row, no DB identity)."""
    def get_available_community(self) -> list[CommunityMachine]: ...
    def get_by_id(self, machine_id: str) -> CommunityMachine | None: ...
    def set_processing(self, machine_id: str) -> None: ...
    def set_available(self, machine_id: str) -> None: ...
    def mark_stale(self) -> None: ...
    def get_failover_candidates(self, exclude_machine_id: str) -> list[CommunityMachine]: ...


class IRenderGroupRepository(Protocol):
    def get_by_id(self, group_id: str) -> dict[str, Any] | None: ...
    def update_status(self, group_id: str, status: str) -> None: ...
    def update_frames(self, group_id: str, *, total_frames: int, frame_start: int, frame_end: int, frame_step: int) -> None: ...
    def create(self, *, group_id: str, input_filename: str, r2_input_key: str, status: str, user_id: str | None, source_asset_id: str | None) -> None: ...
    def full_update(self, group_id: str, **fields: Any) -> None: ...
    def delete(self, group_id: str) -> None: ...


class IUserInputFileRepository(Protocol):
    def upsert(self, *, user_id: str, input_filename: str, r2_key: str, frame_start: int | None, frame_end: int | None, frame_step: int | None, analysis_snapshot_json: str, render_overrides_json: str, scheduling_json: str, used_at: str) -> None: ...
    def list_by_user(self, user_id: str) -> list[dict[str, Any]]: ...
    def get_by_id(self, asset_id: str, user_id: str) -> dict[str, Any] | None: ...
    def rename(self, asset_id: str, display_name: str) -> None: ...
    def delete(self, asset_id: str, user_id: str) -> None: ...


# ---------------------------------------------------------------------------
# Instance Status Provider (per-fleet live status)
# ---------------------------------------------------------------------------

@runtime_checkable
class IInstanceStatusProvider(Protocol):

    @property
    def fleet_type(self) -> str: ...

    def get_all(self) -> list[InstanceSnapshot]: ...

    def get_by_job(self, job_id: str) -> InstanceSnapshot | None: ...


# ---------------------------------------------------------------------------
# Storage
# ---------------------------------------------------------------------------

@runtime_checkable
class IStorageClient(Protocol):
    def upload_file(self, key: str, data: bytes, content_type: str = ...) -> None: ...
    def download_file(self, key: str) -> bytes: ...
    def file_exists(self, key: str) -> bool: ...
    def get_file_size(self, key: str) -> int | None: ...
    def delete_file(self, key: str) -> None: ...
    def list_files(self, prefix: str) -> list[str]: ...
    def generate_presigned_url(self, key: str, expires_in: int = ..., download_name: str | None = ...) -> str: ...
    def generate_presigned_upload_url(self, key: str, content_type: str = ..., expires_in: int = ...) -> str: ...
    def create_multipart_upload(self, key: str, content_type: str = ...) -> str: ...
    def generate_presigned_upload_part_url(self, key: str, upload_id: str, part_number: int, expires_in: int = ...) -> str: ...
    def complete_multipart_upload(self, key: str, upload_id: str, parts: list[dict]) -> dict: ...
    def abort_multipart_upload(self, key: str, upload_id: str) -> None: ...


# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------

@runtime_checkable
class IAuthProvider(Protocol):
    def verify_token(self, token: str) -> dict[str, Any]: ...
    def get_or_create_profile(self, uid: str, email: str | None) -> dict[str, Any]: ...
    def update_profile(self, uid: str, updates: dict[str, Any]) -> None: ...
    def write_render_group_record(self, uid: str, group_id: str, data: dict[str, Any]) -> None: ...
