"""Build anchor scenes for the LLM cost estimator from real telemetry.

Pulls render_telemetry, groups by scene-invariant hash (the same hash
the runtime cache uses), picks the median seconds-per-frame across
each scene's chunks, and writes the top N most-observed scenes to
``allocation_cost_anchor_scenes.json`` -- the file the LLM caller
loads into its system prompt at boot.

Read-only on the DB.  Overwrites the anchor JSON file.

Usage:
    python -m scripts.build_allocation_cost_anchor_scenes

Env required:
    DATABASE_URL    Neon connection string (loaded from serverV2/.env)
"""

from __future__ import annotations

import json
import logging
import statistics
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

# Load serverV2/.env BEFORE importing serverV2 modules that read env
# at import time (notably ``serverV2.infrastructure.db``, which
# reads ``DATABASE_URL`` at module import).
_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(_ROOT / "serverV2" / ".env")

from serverV2.allocation.services.allocation_cost_estimation_service.allocation_cost_file_formula import (
    ANCHOR_GPU,
)
from serverV2.allocation.services.allocation_cost_estimation_service.allocation_cost_file_formula_repository import (
    build_scene_invariant_hash,
)
from serverV2.infrastructure.db import query_all


logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger("build_anchors")


# ---- Tunables -----------------------------------------------------------
# MIN_CHUNKS_PER_SCENE=1 takes every distinct scene; raise once
# telemetry has enough coverage that you can be picky.  Today (Jun 2026)
# only ~8 distinct scenes have telemetry so the cutoff isn't binding.
MIN_CHUNKS_PER_SCENE = 1
MAX_ANCHORS = 25           # cap so the system prompt stays small
# -------------------------------------------------------------------------


OUTPUT_FILE = (
    _ROOT
    / "serverV2"
    / "allocation"
    / "services"
    / "allocation_cost_estimation_service"
    / "allocation_cost_anchor_scenes.json"
)

# config.json holds the per-GPU ``render_speed`` table.  Anchor scenes
# observed on faster GPUs are scaled UP to the anchor GPU (RTX 3090,
# render_speed ~= 1.0) so the LLM sees every measurement on a single
# scale.  Fallback render_speed for GPUs not in the table is 1.0 (treat
# as anchor-equivalent) -- conservative and only matters for the rare
# tail-end GPU.
_GPU_SPEED_CONFIG = _ROOT / "serverV2" / "config.json"


ANCHOR_FILE_COMMENT = (
    "Generated by scripts/build_allocation_cost_anchor_scenes.py from "
    "render_telemetry.  Each entry pairs a real scene's heaviness "
    "dict with the median seconds-per-frame observed for that scene "
    "(at its dominant samples / resolution / GPU).  The LLM caller "
    "embeds the list verbatim into its system prompt as few-shot "
    "calibration anchors.  Re-run this script as telemetry "
    "accumulates."
)


def _load_gpu_speeds() -> dict[str, float]:
    """Build {gpu_name: render_speed} from vast + modal sections of
    config.json.  Lower-cased keys for case-insensitive lookup
    (telemetry has both 'L40S' and 'l40s' from the two providers).
    """
    cfg = json.loads(_GPU_SPEED_CONFIG.read_text(encoding="utf-8"))
    out: dict[str, float] = {}
    for e in cfg.get("vast_instances", []):
        out[str(e["gpu_name"]).lower()] = float(e["render_speed"])
    for e in cfg.get("modal_instances", []):
        out[str(e["gpu_type"]).lower()] = float(e["render_speed"])
    return out


def _gpu_render_speed(gpu_name: str | None, speeds: dict[str, float]) -> float:
    """Lookup with a safe fallback.  Returns 1.0 (anchor-equivalent)
    when the GPU isn't in config.json -- conservative, only matters
    for rare tail-end GPUs (e.g. RTX A5000 in current telemetry).
    """
    if not gpu_name:
        return 1.0
    return speeds.get(gpu_name.lower(), 1.0)


def _load_telemetry() -> list[dict[str, Any]]:
    # Use ``chunk_size`` (always populated on completed chunks) instead
    # of ``rendered_frames`` (currently always 0 -- the telemetry writer
    # never fills it).  Filter to rows where both ``chunk_size`` and
    # ``seconds_total`` are positive so seconds-per-frame is well-defined.
    return query_all(
        """
        SELECT
            heaviness_json,
            gpu_type,
            fleet,
            chunk_size,
            seconds_total
        FROM render_telemetry
        WHERE chunk_size > 0 AND seconds_total > 0
        """
    )


def _mode(values: list[Any]) -> Any:
    """Most common value; ties broken by first occurrence."""
    return Counter(values).most_common(1)[0][0]


def _build_anchors(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    gpu_speeds = _load_gpu_speeds()

    by_scene: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        heaviness = row["heaviness_json"]
        # JSONB returns a dict via psycopg2; defensive type-check
        # so a single bad row doesn't kill the whole run.
        if not isinstance(heaviness, dict):
            continue
        scene_hash = build_scene_invariant_hash(heaviness)
        by_scene[scene_hash].append(row)

    anchors: list[dict[str, Any]] = []
    for scene_rows in by_scene.values():
        if len(scene_rows) < MIN_CHUNKS_PER_SCENE:
            continue
        # Per-chunk: seconds-per-frame on the observation GPU,
        # then scaled UP to the anchor GPU (RTX 3090) by multiplying
        # by render_speed.  This puts every measurement on a single
        # scale so the LLM sees consistent values regardless of which
        # GPU the chunk actually ran on.
        spf_raw = [
            float(r["seconds_total"]) / float(r["chunk_size"])
            for r in scene_rows
        ]
        spf_anchor = [
            raw * _gpu_render_speed(r["gpu_type"], gpu_speeds)
            for raw, r in zip(spf_raw, scene_rows)
        ]
        # All rows in this group share the same invariant subset by
        # construction (same hash) -- the first row's heaviness is
        # representative.  Tunables vary across rows; we report the
        # mode independently below.
        representative_heaviness = scene_rows[0]["heaviness_json"]
        anchors.append({
            "heaviness": representative_heaviness,
            "measurement": {
                "samples": _mode([
                    int(r["heaviness_json"].get("samples", 0) or 0)
                    for r in scene_rows
                ]),
                "resolution_percentage": _mode([
                    int(r["heaviness_json"].get("resolution_percentage", 100) or 100)
                    for r in scene_rows
                ]),
                "observed_on_gpu": _mode([r["gpu_type"] for r in scene_rows]),
                "fleet": _mode([r["fleet"] for r in scene_rows]),
                "raw_seconds_per_frame_on_observed_gpu": round(
                    statistics.median(spf_raw), 2,
                ),
                "seconds_per_frame_at_anchor_gpu": round(
                    statistics.median(spf_anchor), 2,
                ),
                "chunk_count": len(scene_rows),
            },
        })

    # Rank by sample size -- most-observed scenes are the strongest
    # anchors.  Cap at MAX_ANCHORS to keep the system prompt small.
    anchors.sort(key=lambda a: a["measurement"]["chunk_count"], reverse=True)
    return anchors[:MAX_ANCHORS]


def main() -> None:
    log.info("Querying render_telemetry...")
    rows = _load_telemetry()
    log.info("  loaded %d rows", len(rows))

    anchors = _build_anchors(rows)
    log.info(
        "  built %d anchors (kept scenes with >= %d chunks, top %d by chunk count)",
        len(anchors), MIN_CHUNKS_PER_SCENE, MAX_ANCHORS,
    )

    payload = {
        "_comment": ANCHOR_FILE_COMMENT,
        "anchors": anchors,
    }
    OUTPUT_FILE.write_text(
        json.dumps(payload, indent=2),
        encoding="utf-8",
    )
    log.info("Wrote %s", OUTPUT_FILE)


if __name__ == "__main__":
    main()
